### ISSUE TITLE
How to run this on windows and Embedded python

### ISSUE THREAD

**Issue by veso266** [peterkvt80/vbit-iv#2]
Hi there, since I am on windows (and using python2) I decided to give this a go: [python-3.7.2-amd64-vbit-iv.zip](http://downloads.dxing.si/konzola/download.php?file=python-3.7.2-amd64-vbit-iv.zip)

![slika](https://user-images.githubusercontent.com/6347325/142779831-79053fd3-9b66-495e-a6dc-834950041a37.png)

extraxt to a folder where you want and your teletext folder with pages resides
run it like this
```
vbit2 --dir teefax | python38\python.exe vbit-iv.py 1 0
```
teefax is a folder containing teletext pages (BBC100.ttix, BBC101.ttix , etc)

The onlything that doesn't work is remote-control since I wasn't able to get ZeroMQ working on portable python (embedded python) distro, but the rest works

Hopefully someone finds that usefull

**Comment by peterkvt80** [comment]
Thanks. that is very helpful. What you are missing are the teletext2 and teletext4 fonts. I'm going to try my own install and put it on the Wiki.

**Comment by peterkvt80** [comment]
Windows installation procedure in https://github.com/peterkvt80/vbit-iv/wiki/Using-vbit-iv-on-Windows
