### ISSUE TITLE
Query re running in terminal

### ISSUE THREAD

**Issue by palmergit** [peterkvt80/vbit-iv#3]
Followed install on PI zero. Correct OS, clean install. Connecting through SSH. I get the below error related to DISPLAY. When you are running this are you doing so using terminal in GUI? Just trying to figure the best fix.

Traceback (most recent call last):
  File "/home/al/vbit2/vbit-iv/./vbit-iv.py", line 59, in <module>
    ttx = TTXpage()
  File "/home/al/vbit2/vbit-iv/ttxpage.py", line 48, in __init__
    self.root = Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by peterkvt80** [comment]
Yes, you need to be running a display or it has nowhere to open the window. It draws teletext onto whatever screen you have.

**Comment by palmergit** [comment]
Thank you, will give it another go.
